apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble
  namespace: openshift-gitops
spec:
  destination:
    namespace: sandbox
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: bubble/mainfest
    repoURL: https://github.com/marek100/argocd-public
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=false